export const types = {
    //SYNC
    FILL_TODOS:        'FILL_TODOS',
    CREATE_TODO:       'CREATE_TODO',
    REMOVE_TODO:       'REMOVE_TODO',
    UPDATE_TODO:       'UPDATE_TODO',
    COMPLETE_ALL_TODO: 'COMPLETE_ALL_TODO',

    //ASYNC
    FETCH_TODOS_ASYNC:       'FETCH_TODOS_ASYNC',
    CREATE_TODO_ASYNC:       'CREATE_TODO_ASYNC',
    REMOVE_TODO_ASYNC:       'REMOVE_TODO_ASYNC',
    UPDATE_TODO_ASYNC:       'UPDATE_TODO_ASYNC',
    COMPLETE_ALL_TODO_ASYNC: 'COMPLETE_ALL_TODO_ASYNC',

};
