export const types = {
    //SYNC
    FILL_TODOS:  'FILL_TODOS',
    CREATE_POST: 'CREATE_POST',
    CLEAR_POSTS: 'CLEAR_POSTS',
    REMOVE_POST: 'REMOVE_POST',

    //ASYNC
    FETCH_TODOS_ASYNC: 'FETCH_TODOS_ASYNC',
    CREATE_POST_ASYNC: 'CREATE_POST_ASYNC',
    REMOVE_POST_ASYNC: 'REMOVE_POST_ASYNC',
};
